// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import EditReleaseController from "./edit_release_controller"
application.register("edit-release", EditReleaseController)

import GenresTomSelectController from "./genres_tom_select_controller"
application.register("genres-tom-select", GenresTomSelectController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)
